"""changed_column_name_in_transaction_model

Revision ID: 28609dd72173
Revises: a59db7ee08c5
Create Date: 2025-06-19 12:57:04.406255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28609dd72173'
down_revision: Union[str, None] = 'a59db7ee08c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotencykey', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.drop_column('idempotencykey', 'expired_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotencykey', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('idempotencykey', 'expires_at')
    # ### end Alembic commands ###
